### ISSUE TITLE
Feature Todo

### ISSUE THREAD

**Issue by TehNut** [TehNut-Mods/LoreExpansion#1]
Just putting the list of features Cyanide puked out down in a checklist format.
- [x] Multi-language support
- [x] Command block trigger to provide lore to a player (inventory free trigger)
- [x] Themed books (classic, tech, magic, etc)
- [x] Action system to provide lore to a player (reach X coord, get X item, etc. tldr: basic event system)
- [x] Serverside only mode (download lore set when connecting to server) **If this is done, it will be done _far_ in the future**
- [x] A way to sort pages after they've been added
- [x] NMS milestone thing
- [x] Center the GUI
- [x] Paginate categories to support >35 lore entries. Scroll or buttons. There's already groundwork for both.
- [x] Define lore that is unlocked by default.
- [ ] Mod integration
- [ ] Waypoints
- [ ] Volume settings for lore audio
- [ ] Ingame GUI for editing lore instead of JSON text editing
- [ ] Image support.
- [ ] Crafting recipe support (show recipes in the page).

**Comment by TehNut** [comment]
Command block trigger done https://streamable.com/8rml

**Comment by TehNut** [comment]
Localization support for lore titles, categories, and body text as of 45d99bbe604e15b1a89d5e94114fd33c6990e65d

**Comment by CyanideX** [comment]
Added a few things to the list. ;)

**Comment by MokahTGS** [comment]
The in game way of adding or editing lore is huge.  Is there a way of reloading json files while in game or do you have to reload the game to see changes?

**Comment by TehNut** [comment]
`/lore reload`

**Comment by dragon3025** [comment]
Is there a way to give each lore its own icon?

**Comment by TehNut** [comment]
No and I do not plan on supporting that.

**Comment by johbii** [comment]
Any chance in hell you could add youtube or similar video support for quest tutorials?

**Comment by CyanideX** [comment]
Embedded video in a journal does not fit with the theme of the mod.

**Comment by SeriousCreeper** [comment]
Curious if the image feature is still being planned and/ore in work? 
Currently working on a story based modpack, and having little images of scribbles/discoveries in those pages would be amazing :D

**Comment by TehNut** [comment]
It's something I'd like to implement but it requires more GL knowledge than I currently have. I wouldn't exactly call myself a rendering expert.

**Comment by SeriousCreeper** [comment]
Makes sense! Don't know too much about it myself unfortunately. Perhaps looking at how Enchiridion, or FTB Guides or something loads/displays them may help?

**Comment by TehNut** [comment]
The loading and displaying is the easy part. The scissoring of the image (so it doesn't overflow passed the bottom of the page) and rewriting of how scrolling works to support that scissoring is the hard part.
